name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
     - assets/Profile.jpg

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  http: ^1.1.0
